export const ENV_SLS_STAGE = 'SLS_STAGE';
export const ENV_CORS_DOMAINS = 'CORS_DOMAINS';
export const ENV_OPEN_API_SERVERS = 'OPEN_API_SERVERS';
export const ENV_OPEN_API_SAVE_FILE = 'OPEN_API_SAVE_FILE';
