export const AWS_REGION = 'AWS_REGION';
export const AWS_SSM_OPTIONS = 'AWS_SSM_OPTIONS';
export const AWS_SSM_PARAMETERS = 'AWS_SSM_PARAMETERS';
export const AWS_SECRETS_MANAGER_OPTIONS = 'AWS_SECRETS_MANAGER_OPTIONS';
export const AWS_SECRETS_MANAGER_PARAMETERS = 'AWS_SECRETS_MANAGER_PARAMETERS';
